// config.example.js
// COPY THIS FILE AND RENAME IT TO config.js
// THEN ENTER YOUR ACTUAL KEYS BELOW. DO NOT COMMIT config.js TO GITHUB.

const SUPABASE_URL = 'YOUR_SUPABASE_URL_HERE';
const SUPABASE_ANON_KEY = 'YOUR_SUPABASE_ANON_KEY_HERE';